[custom.all.gnuplot]
type = "local"
path = "."
ipkg = "gnuplot.ipkg"

[custom.all.gnuplot-example]
type = "local"
path = "example"
ipkg = "example.ipkg"

[custom.all.rio]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-rio"
commit = "latest:main"
ipkg   = "rio.ipkg"

[custom.all.filepath]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-filepath"
commit = "latest:main"
ipkg   = "filepath.ipkg"
