[custom.all.gnuplot]
type   = "local"
path   = "."
ipkg   = "gnuplot.ipkg"

[custom.all.gnuplot-example]
type   = "local"
path   = "example"
ipkg   = "example.ipkg"

[custom.all.rio]
type   = "local"
path   = "../rio"
ipkg   = "rio.ipkg"
